// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new operations API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for operations API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetConfigContainer(params *GetConfigContainerParams) (*GetConfigContainerOK, error)

	GetPoolContainer(params *GetPoolContainerParams) (*GetPoolContainerOK, error)

	Ping(params *PingParams) (*PingOK, error)

	V1CreateLoadBalancerPool(params *V1CreateLoadBalancerPoolParams) (*V1CreateLoadBalancerPoolOK, error)

	V1DeleteLoadBalancerArtifact(params *V1DeleteLoadBalancerArtifactParams) (*V1DeleteLoadBalancerArtifactOK, *V1DeleteLoadBalancerArtifactNoContent, error)

	V1DeleteLoadBalancerPool(params *V1DeleteLoadBalancerPoolParams) (*V1DeleteLoadBalancerPoolNoContent, error)

	V1GetConfig(params *V1GetConfigParams) (*V1GetConfigOK, error)

	V1GetLoadBalancerArtifact(params *V1GetLoadBalancerArtifactParams) (*V1GetLoadBalancerArtifactOK, error)

	V1GetLoadBalancerArtifacts(params *V1GetLoadBalancerArtifactsParams) (*V1GetLoadBalancerArtifactsOK, error)

	V1GetLoadBalancerPool(params *V1GetLoadBalancerPoolParams) (*V1GetLoadBalancerPoolOK, error)

	V1GetLoadBalancerPools(params *V1GetLoadBalancerPoolsParams) (*V1GetLoadBalancerPoolsOK, error)

	V1Ping(params *V1PingParams) (*V1PingOK, error)

	V1UpdateConfig(params *V1UpdateConfigParams) (*V1UpdateConfigOK, error)

	V1UpdateLoadBalancerArtifact(params *V1UpdateLoadBalancerArtifactParams) (*V1UpdateLoadBalancerArtifactOK, error)

	V1UpdateLoadBalancerPool(params *V1UpdateLoadBalancerPoolParams) (*V1UpdateLoadBalancerPoolOK, error)

	V1Version(params *V1VersionParams) (*V1VersionOK, error)

	V2CreatePool(params *V2CreatePoolParams) (*V2CreatePoolOK, error)

	V2CreatePoolTemplate(params *V2CreatePoolTemplateParams) (*V2CreatePoolTemplateOK, error)

	V2DeleteLBTemplate(params *V2DeleteLBTemplateParams) (*V2DeleteLBTemplateOK, error)

	V2DeletePool(params *V2DeletePoolParams) (*V2DeletePoolNoContent, error)

	V2DeletePoolTemplate(params *V2DeletePoolTemplateParams) (*V2DeletePoolTemplateNoContent, error)

	V2DeletePoolTemplateConfigTemplate(params *V2DeletePoolTemplateConfigTemplateParams) (*V2DeletePoolTemplateConfigTemplateOK, error)

	V2GetConfig(params *V2GetConfigParams) (*V2GetConfigOK, error)

	V2GetDefaultLBTemplate(params *V2GetDefaultLBTemplateParams) (*V2GetDefaultLBTemplateOK, error)

	V2GetLBConfig(params *V2GetLBConfigParams) (*V2GetLBConfigOK, error)

	V2GetLBTemplate(params *V2GetLBTemplateParams) (*V2GetLBTemplateOK, error)

	V2GetPool(params *V2GetPoolParams) (*V2GetPoolOK, error)

	V2GetPoolMetadata(params *V2GetPoolMetadataParams) (*V2GetPoolMetadataOK, error)

	V2GetPoolTemplateConfigTemplate(params *V2GetPoolTemplateConfigTemplateParams) (*V2GetPoolTemplateConfigTemplateOK, error)

	V2GetPoolTemplateStatus(params *V2GetPoolTemplateStatusParams) (*V2GetPoolTemplateStatusOK, error)

	V2GetPoolTemplates(params *V2GetPoolTemplatesParams) (*V2GetPoolTemplatesOK, error)

	V2GetPools(params *V2GetPoolsParams) (*V2GetPoolsOK, error)

	V2UpdateLBTemplate(params *V2UpdateLBTemplateParams) (*V2UpdateLBTemplateOK, error)

	V2UpdatePool(params *V2UpdatePoolParams) (*V2UpdatePoolOK, error)

	V2UpdatePoolTemplateConfigTemplate(params *V2UpdatePoolTemplateConfigTemplateParams) (*V2UpdatePoolTemplateConfigTemplateOK, error)

	Version(params *VersionParams) (*VersionOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetConfigContainer Get the entire configuration object including v1 and v2 pools.
*/
func (a *Client) GetConfigContainer(params *GetConfigContainerParams) (*GetConfigContainerOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetConfigContainerParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetConfigContainer",
		Method:             "GET",
		PathPattern:        "/config",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetConfigContainerReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetConfigContainerOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetConfigContainerDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  GetPoolContainer Returns a v1 or v2 load balancer pool based on a single name.
*/
func (a *Client) GetPoolContainer(params *GetPoolContainerParams) (*GetPoolContainerOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetPoolContainerParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetPoolContainer",
		Method:             "GET",
		PathPattern:        "/pools/{name}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetPoolContainerReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetPoolContainerOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetPoolContainerDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  Ping Healthcheck endpoint.
*/
func (a *Client) Ping(params *PingParams) (*PingOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPingParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Ping",
		Method:             "GET",
		PathPattern:        "/ping",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PingReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PingOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*PingDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  V1CreateLoadBalancerPool Creates a new load balancer pool.
*/
func (a *Client) V1CreateLoadBalancerPool(params *V1CreateLoadBalancerPoolParams) (*V1CreateLoadBalancerPoolOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV1CreateLoadBalancerPoolParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "V1CreateLoadBalancerPool",
		Method:             "POST",
		PathPattern:        "/v1/loadbalancers",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V1CreateLoadBalancerPoolReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V1CreateLoadBalancerPoolOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V1CreateLoadBalancerPoolDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  V1DeleteLoadBalancerArtifact Clears an override for a artifact. Not all artifacts can be deleted.
*/
func (a *Client) V1DeleteLoadBalancerArtifact(params *V1DeleteLoadBalancerArtifactParams) (*V1DeleteLoadBalancerArtifactOK, *V1DeleteLoadBalancerArtifactNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV1DeleteLoadBalancerArtifactParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "V1DeleteLoadBalancerArtifact",
		Method:             "DELETE",
		PathPattern:        "/v1/loadbalancers/{name}/artifacts/{artifactName}",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V1DeleteLoadBalancerArtifactReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, nil, err
	}
	switch value := result.(type) {
	case *V1DeleteLoadBalancerArtifactOK:
		return value, nil, nil
	case *V1DeleteLoadBalancerArtifactNoContent:
		return nil, value, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V1DeleteLoadBalancerArtifactDefault)
	return nil, nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  V1DeleteLoadBalancerPool Deletes a single load balancer pool based on the name supplied.
*/
func (a *Client) V1DeleteLoadBalancerPool(params *V1DeleteLoadBalancerPoolParams) (*V1DeleteLoadBalancerPoolNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV1DeleteLoadBalancerPoolParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "V1DeleteLoadBalancerPool",
		Method:             "DELETE",
		PathPattern:        "/v1/loadbalancers/{name}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V1DeleteLoadBalancerPoolReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V1DeleteLoadBalancerPoolNoContent)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V1DeleteLoadBalancerPoolDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  V1GetConfig Get the entire configuration.
*/
func (a *Client) V1GetConfig(params *V1GetConfigParams) (*V1GetConfigOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV1GetConfigParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "V1GetConfig",
		Method:             "GET",
		PathPattern:        "/v1/all",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V1GetConfigReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V1GetConfigOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V1GetConfigDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  V1GetLoadBalancerArtifact Returns an configuration artifact for a load balancer pool.
*/
func (a *Client) V1GetLoadBalancerArtifact(params *V1GetLoadBalancerArtifactParams) (*V1GetLoadBalancerArtifactOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV1GetLoadBalancerArtifactParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "V1GetLoadBalancerArtifact",
		Method:             "GET",
		PathPattern:        "/v1/loadbalancers/{name}/artifacts/{artifactName}",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V1GetLoadBalancerArtifactReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V1GetLoadBalancerArtifactOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V1GetLoadBalancerArtifactDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  V1GetLoadBalancerArtifacts Returns artifacts available for a load balancer pool.
*/
func (a *Client) V1GetLoadBalancerArtifacts(params *V1GetLoadBalancerArtifactsParams) (*V1GetLoadBalancerArtifactsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV1GetLoadBalancerArtifactsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "V1GetLoadBalancerArtifacts",
		Method:             "GET",
		PathPattern:        "/v1/loadbalancers/{name}/artifacts",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V1GetLoadBalancerArtifactsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V1GetLoadBalancerArtifactsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V1GetLoadBalancerArtifactsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  V1GetLoadBalancerPool Returns a load balancer pool based on a single name.
*/
func (a *Client) V1GetLoadBalancerPool(params *V1GetLoadBalancerPoolParams) (*V1GetLoadBalancerPoolOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV1GetLoadBalancerPoolParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "V1GetLoadBalancerPool",
		Method:             "GET",
		PathPattern:        "/v1/loadbalancers/{name}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V1GetLoadBalancerPoolReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V1GetLoadBalancerPoolOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V1GetLoadBalancerPoolDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  V1GetLoadBalancerPools Get all load balancer pools.
*/
func (a *Client) V1GetLoadBalancerPools(params *V1GetLoadBalancerPoolsParams) (*V1GetLoadBalancerPoolsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV1GetLoadBalancerPoolsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "V1GetLoadBalancerPools",
		Method:             "GET",
		PathPattern:        "/v1/loadbalancers",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V1GetLoadBalancerPoolsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V1GetLoadBalancerPoolsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V1GetLoadBalancerPoolsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  V1Ping Healthcheck endpoint.
*/
func (a *Client) V1Ping(params *V1PingParams) (*V1PingOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV1PingParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "V1Ping",
		Method:             "GET",
		PathPattern:        "/v1/ping",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V1PingReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V1PingOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V1PingDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  V1UpdateConfig Wipes and overwrites the entire configuration.
*/
func (a *Client) V1UpdateConfig(params *V1UpdateConfigParams) (*V1UpdateConfigOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV1UpdateConfigParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "V1UpdateConfig",
		Method:             "PUT",
		PathPattern:        "/v1/all",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V1UpdateConfigReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V1UpdateConfigOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V1UpdateConfigDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  V1UpdateLoadBalancerArtifact Creates or updates an configuration artifact for a load balancer pool. Not all artifacts can be changed.
*/
func (a *Client) V1UpdateLoadBalancerArtifact(params *V1UpdateLoadBalancerArtifactParams) (*V1UpdateLoadBalancerArtifactOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV1UpdateLoadBalancerArtifactParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "V1UpdateLoadBalancerArtifact",
		Method:             "PUT",
		PathPattern:        "/v1/loadbalancers/{name}/artifacts/{artifactName}",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V1UpdateLoadBalancerArtifactReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V1UpdateLoadBalancerArtifactOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V1UpdateLoadBalancerArtifactDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  V1UpdateLoadBalancerPool Updates a new load balancer pool.
*/
func (a *Client) V1UpdateLoadBalancerPool(params *V1UpdateLoadBalancerPoolParams) (*V1UpdateLoadBalancerPoolOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV1UpdateLoadBalancerPoolParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "V1UpdateLoadBalancerPool",
		Method:             "PUT",
		PathPattern:        "/v1/loadbalancers/{name}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V1UpdateLoadBalancerPoolReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V1UpdateLoadBalancerPoolOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V1UpdateLoadBalancerPoolDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  V1Version Returns the installed Edge-LB package version.
*/
func (a *Client) V1Version(params *V1VersionParams) (*V1VersionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV1VersionParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "V1Version",
		Method:             "GET",
		PathPattern:        "/v1/version",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V1VersionReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V1VersionOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V1VersionDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  V2CreatePool Creates a new load balancer pool.
*/
func (a *Client) V2CreatePool(params *V2CreatePoolParams) (*V2CreatePoolOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV2CreatePoolParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "V2CreatePool",
		Method:             "POST",
		PathPattern:        "/v2/pools",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V2CreatePoolReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V2CreatePoolOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V2CreatePoolDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  V2CreatePoolTemplate Create a pool template
*/
func (a *Client) V2CreatePoolTemplate(params *V2CreatePoolTemplateParams) (*V2CreatePoolTemplateOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV2CreatePoolTemplateParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "V2CreatePoolTemplate",
		Method:             "POST",
		PathPattern:        "/v2/pooltemplates",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V2CreatePoolTemplateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V2CreatePoolTemplateOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V2CreatePoolTemplateDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  V2DeleteLBTemplate Resets the lb config template to default for a pool.
*/
func (a *Client) V2DeleteLBTemplate(params *V2DeleteLBTemplateParams) (*V2DeleteLBTemplateOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV2DeleteLBTemplateParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "V2DeleteLBTemplate",
		Method:             "DELETE",
		PathPattern:        "/v2/pools/{name}/lbtemplate",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V2DeleteLBTemplateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V2DeleteLBTemplateOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V2DeleteLBTemplateDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  V2DeletePool Deletes a single load balancer pool based on the name supplied.
*/
func (a *Client) V2DeletePool(params *V2DeletePoolParams) (*V2DeletePoolNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV2DeletePoolParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "V2DeletePool",
		Method:             "DELETE",
		PathPattern:        "/v2/pools/{name}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V2DeletePoolReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V2DeletePoolNoContent)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V2DeletePoolDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  V2DeletePoolTemplate Delete a pool template and the pool generated by this pool template.
*/
func (a *Client) V2DeletePoolTemplate(params *V2DeletePoolTemplateParams) (*V2DeletePoolTemplateNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV2DeletePoolTemplateParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "V2DeletePoolTemplate",
		Method:             "DELETE",
		PathPattern:        "/v2/pooltemplates/{name}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V2DeletePoolTemplateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V2DeletePoolTemplateNoContent)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V2DeletePoolTemplateDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  V2DeletePoolTemplateConfigTemplate Resets the pool configuration template to default
*/
func (a *Client) V2DeletePoolTemplateConfigTemplate(params *V2DeletePoolTemplateConfigTemplateParams) (*V2DeletePoolTemplateConfigTemplateOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV2DeletePoolTemplateConfigTemplateParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "V2DeletePoolTemplateConfigTemplate",
		Method:             "DELETE",
		PathPattern:        "/v2/pooltemplates/{name}/template",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V2DeletePoolTemplateConfigTemplateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V2DeletePoolTemplateConfigTemplateOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V2DeletePoolTemplateConfigTemplateDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  V2GetConfig Get the entire configuration object including only v2 pools.
*/
func (a *Client) V2GetConfig(params *V2GetConfigParams) (*V2GetConfigOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV2GetConfigParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "V2GetConfig",
		Method:             "GET",
		PathPattern:        "/v2/config",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V2GetConfigReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V2GetConfigOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V2GetConfigDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  V2GetDefaultLBTemplate Returns the default lb config template.
*/
func (a *Client) V2GetDefaultLBTemplate(params *V2GetDefaultLBTemplateParams) (*V2GetDefaultLBTemplateOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV2GetDefaultLBTemplateParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "V2GetDefaultLBTemplate",
		Method:             "GET",
		PathPattern:        "/v2/lbtemplate",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V2GetDefaultLBTemplateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V2GetDefaultLBTemplateOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V2GetDefaultLBTemplateDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  V2GetLBConfig Returns the rendered lb config for a pool.
*/
func (a *Client) V2GetLBConfig(params *V2GetLBConfigParams) (*V2GetLBConfigOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV2GetLBConfigParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "V2GetLBConfig",
		Method:             "GET",
		PathPattern:        "/v2/pools/{name}/lbconfig",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V2GetLBConfigReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V2GetLBConfigOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V2GetLBConfigDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  V2GetLBTemplate Returns the lb config template for a pool.
*/
func (a *Client) V2GetLBTemplate(params *V2GetLBTemplateParams) (*V2GetLBTemplateOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV2GetLBTemplateParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "V2GetLBTemplate",
		Method:             "GET",
		PathPattern:        "/v2/pools/{name}/lbtemplate",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V2GetLBTemplateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V2GetLBTemplateOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V2GetLBTemplateDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  V2GetPool Returns a v2 load balancer pool based on a single name.
*/
func (a *Client) V2GetPool(params *V2GetPoolParams) (*V2GetPoolOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV2GetPoolParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "V2GetPool",
		Method:             "GET",
		PathPattern:        "/v2/pools/{name}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V2GetPoolReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V2GetPoolOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V2GetPoolDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  V2GetPoolMetadata Returns the ELB metadata for a pool.
*/
func (a *Client) V2GetPoolMetadata(params *V2GetPoolMetadataParams) (*V2GetPoolMetadataOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV2GetPoolMetadataParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "V2GetPoolMetadata",
		Method:             "GET",
		PathPattern:        "/v2/pools/{name}/metadata",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V2GetPoolMetadataReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V2GetPoolMetadataOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V2GetPoolMetadataDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  V2GetPoolTemplateConfigTemplate Returns the pool configuration template for the pool template.
*/
func (a *Client) V2GetPoolTemplateConfigTemplate(params *V2GetPoolTemplateConfigTemplateParams) (*V2GetPoolTemplateConfigTemplateOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV2GetPoolTemplateConfigTemplateParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "V2GetPoolTemplateConfigTemplate",
		Method:             "GET",
		PathPattern:        "/v2/pooltemplates/{name}/template",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V2GetPoolTemplateConfigTemplateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V2GetPoolTemplateConfigTemplateOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V2GetPoolTemplateConfigTemplateDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  V2GetPoolTemplateStatus Get the status for each pool for a given pool template, e.g. rendering information.
*/
func (a *Client) V2GetPoolTemplateStatus(params *V2GetPoolTemplateStatusParams) (*V2GetPoolTemplateStatusOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV2GetPoolTemplateStatusParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "V2GetPoolTemplateStatus",
		Method:             "GET",
		PathPattern:        "/v2/pooltemplates/{name}/status",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V2GetPoolTemplateStatusReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V2GetPoolTemplateStatusOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V2GetPoolTemplateStatusDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  V2GetPoolTemplates List all pool templates.
*/
func (a *Client) V2GetPoolTemplates(params *V2GetPoolTemplatesParams) (*V2GetPoolTemplatesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV2GetPoolTemplatesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "V2GetPoolTemplates",
		Method:             "GET",
		PathPattern:        "/v2/pooltemplates",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V2GetPoolTemplatesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V2GetPoolTemplatesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V2GetPoolTemplatesDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  V2GetPools Get all load balancer pools.
*/
func (a *Client) V2GetPools(params *V2GetPoolsParams) (*V2GetPoolsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV2GetPoolsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "V2GetPools",
		Method:             "GET",
		PathPattern:        "/v2/pools",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V2GetPoolsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V2GetPoolsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V2GetPoolsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  V2UpdateLBTemplate Creates or updates the lb config template for a pool.
*/
func (a *Client) V2UpdateLBTemplate(params *V2UpdateLBTemplateParams) (*V2UpdateLBTemplateOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV2UpdateLBTemplateParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "V2UpdateLBTemplate",
		Method:             "PUT",
		PathPattern:        "/v2/pools/{name}/lbtemplate",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V2UpdateLBTemplateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V2UpdateLBTemplateOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V2UpdateLBTemplateDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  V2UpdatePool Updates a new load balancer pool.
*/
func (a *Client) V2UpdatePool(params *V2UpdatePoolParams) (*V2UpdatePoolOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV2UpdatePoolParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "V2UpdatePool",
		Method:             "PUT",
		PathPattern:        "/v2/pools/{name}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V2UpdatePoolReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V2UpdatePoolOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V2UpdatePoolDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  V2UpdatePoolTemplateConfigTemplate Updates the pool configuration template.
*/
func (a *Client) V2UpdatePoolTemplateConfigTemplate(params *V2UpdatePoolTemplateConfigTemplateParams) (*V2UpdatePoolTemplateConfigTemplateOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV2UpdatePoolTemplateConfigTemplateParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "V2UpdatePoolTemplateConfigTemplate",
		Method:             "PUT",
		PathPattern:        "/v2/pooltemplates/{name}/template",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V2UpdatePoolTemplateConfigTemplateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V2UpdatePoolTemplateConfigTemplateOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V2UpdatePoolTemplateConfigTemplateDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  Version Returns the installed Edge-LB package version.
*/
func (a *Client) Version(params *VersionParams) (*VersionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewVersionParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Version",
		Method:             "GET",
		PathPattern:        "/version",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &VersionReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*VersionOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*VersionDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
