// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/iss-lab/edgelb-config-helper/models"
)

// V2DeletePoolTemplateConfigTemplateReader is a Reader for the V2DeletePoolTemplateConfigTemplate structure.
type V2DeletePoolTemplateConfigTemplateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V2DeletePoolTemplateConfigTemplateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV2DeletePoolTemplateConfigTemplateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewV2DeletePoolTemplateConfigTemplateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewV2DeletePoolTemplateConfigTemplateOK creates a V2DeletePoolTemplateConfigTemplateOK with default headers values
func NewV2DeletePoolTemplateConfigTemplateOK() *V2DeletePoolTemplateConfigTemplateOK {
	return &V2DeletePoolTemplateConfigTemplateOK{}
}

/*V2DeletePoolTemplateConfigTemplateOK handles this case with default header values.

Updated pool configuration template for pool template.
*/
type V2DeletePoolTemplateConfigTemplateOK struct {
	Payload string
}

func (o *V2DeletePoolTemplateConfigTemplateOK) Error() string {
	return fmt.Sprintf("[DELETE /v2/pooltemplates/{name}/template][%d] v2DeletePoolTemplateConfigTemplateOK  %+v", 200, o.Payload)
}

func (o *V2DeletePoolTemplateConfigTemplateOK) GetPayload() string {
	return o.Payload
}

func (o *V2DeletePoolTemplateConfigTemplateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2DeletePoolTemplateConfigTemplateDefault creates a V2DeletePoolTemplateConfigTemplateDefault with default headers values
func NewV2DeletePoolTemplateConfigTemplateDefault(code int) *V2DeletePoolTemplateConfigTemplateDefault {
	return &V2DeletePoolTemplateConfigTemplateDefault{
		_statusCode: code,
	}
}

/*V2DeletePoolTemplateConfigTemplateDefault handles this case with default header values.

Unexpected error.
*/
type V2DeletePoolTemplateConfigTemplateDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the v2 delete pool template config template default response
func (o *V2DeletePoolTemplateConfigTemplateDefault) Code() int {
	return o._statusCode
}

func (o *V2DeletePoolTemplateConfigTemplateDefault) Error() string {
	return fmt.Sprintf("[DELETE /v2/pooltemplates/{name}/template][%d] V2DeletePoolTemplateConfigTemplate default  %+v", o._statusCode, o.Payload)
}

func (o *V2DeletePoolTemplateConfigTemplateDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *V2DeletePoolTemplateConfigTemplateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
