// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/iss-lab/edgelb-config-helper/models"
)

// V2GetPoolTemplateStatusReader is a Reader for the V2GetPoolTemplateStatus structure.
type V2GetPoolTemplateStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V2GetPoolTemplateStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV2GetPoolTemplateStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewV2GetPoolTemplateStatusDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewV2GetPoolTemplateStatusOK creates a V2GetPoolTemplateStatusOK with default headers values
func NewV2GetPoolTemplateStatusOK() *V2GetPoolTemplateStatusOK {
	return &V2GetPoolTemplateStatusOK{}
}

/*V2GetPoolTemplateStatusOK handles this case with default header values.

Pool template status response.
*/
type V2GetPoolTemplateStatusOK struct {
	Payload models.PoolTemplateStatus
}

func (o *V2GetPoolTemplateStatusOK) Error() string {
	return fmt.Sprintf("[GET /v2/pooltemplates/{name}/status][%d] v2GetPoolTemplateStatusOK  %+v", 200, o.Payload)
}

func (o *V2GetPoolTemplateStatusOK) GetPayload() models.PoolTemplateStatus {
	return o.Payload
}

func (o *V2GetPoolTemplateStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2GetPoolTemplateStatusDefault creates a V2GetPoolTemplateStatusDefault with default headers values
func NewV2GetPoolTemplateStatusDefault(code int) *V2GetPoolTemplateStatusDefault {
	return &V2GetPoolTemplateStatusDefault{
		_statusCode: code,
	}
}

/*V2GetPoolTemplateStatusDefault handles this case with default header values.

Unexpected error.
*/
type V2GetPoolTemplateStatusDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the v2 get pool template status default response
func (o *V2GetPoolTemplateStatusDefault) Code() int {
	return o._statusCode
}

func (o *V2GetPoolTemplateStatusDefault) Error() string {
	return fmt.Sprintf("[GET /v2/pooltemplates/{name}/status][%d] V2GetPoolTemplateStatus default  %+v", o._statusCode, o.Payload)
}

func (o *V2GetPoolTemplateStatusDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *V2GetPoolTemplateStatusDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
