// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/iss-lab/edgelb-config-helper/models"
)

// V2GetPoolTemplateConfigTemplateReader is a Reader for the V2GetPoolTemplateConfigTemplate structure.
type V2GetPoolTemplateConfigTemplateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V2GetPoolTemplateConfigTemplateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV2GetPoolTemplateConfigTemplateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewV2GetPoolTemplateConfigTemplateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewV2GetPoolTemplateConfigTemplateOK creates a V2GetPoolTemplateConfigTemplateOK with default headers values
func NewV2GetPoolTemplateConfigTemplateOK() *V2GetPoolTemplateConfigTemplateOK {
	return &V2GetPoolTemplateConfigTemplateOK{}
}

/*V2GetPoolTemplateConfigTemplateOK handles this case with default header values.

Pool configuration template
*/
type V2GetPoolTemplateConfigTemplateOK struct {
	Payload string
}

func (o *V2GetPoolTemplateConfigTemplateOK) Error() string {
	return fmt.Sprintf("[GET /v2/pooltemplates/{name}/template][%d] v2GetPoolTemplateConfigTemplateOK  %+v", 200, o.Payload)
}

func (o *V2GetPoolTemplateConfigTemplateOK) GetPayload() string {
	return o.Payload
}

func (o *V2GetPoolTemplateConfigTemplateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2GetPoolTemplateConfigTemplateDefault creates a V2GetPoolTemplateConfigTemplateDefault with default headers values
func NewV2GetPoolTemplateConfigTemplateDefault(code int) *V2GetPoolTemplateConfigTemplateDefault {
	return &V2GetPoolTemplateConfigTemplateDefault{
		_statusCode: code,
	}
}

/*V2GetPoolTemplateConfigTemplateDefault handles this case with default header values.

Unexpected error.
*/
type V2GetPoolTemplateConfigTemplateDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the v2 get pool template config template default response
func (o *V2GetPoolTemplateConfigTemplateDefault) Code() int {
	return o._statusCode
}

func (o *V2GetPoolTemplateConfigTemplateDefault) Error() string {
	return fmt.Sprintf("[GET /v2/pooltemplates/{name}/template][%d] V2GetPoolTemplateConfigTemplate default  %+v", o._statusCode, o.Payload)
}

func (o *V2GetPoolTemplateConfigTemplateDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *V2GetPoolTemplateConfigTemplateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
