// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewV2UpdatePoolTemplateConfigTemplateParams creates a new V2UpdatePoolTemplateConfigTemplateParams object
// with the default values initialized.
func NewV2UpdatePoolTemplateConfigTemplateParams() *V2UpdatePoolTemplateConfigTemplateParams {
	var ()
	return &V2UpdatePoolTemplateConfigTemplateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV2UpdatePoolTemplateConfigTemplateParamsWithTimeout creates a new V2UpdatePoolTemplateConfigTemplateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV2UpdatePoolTemplateConfigTemplateParamsWithTimeout(timeout time.Duration) *V2UpdatePoolTemplateConfigTemplateParams {
	var ()
	return &V2UpdatePoolTemplateConfigTemplateParams{

		timeout: timeout,
	}
}

// NewV2UpdatePoolTemplateConfigTemplateParamsWithContext creates a new V2UpdatePoolTemplateConfigTemplateParams object
// with the default values initialized, and the ability to set a context for a request
func NewV2UpdatePoolTemplateConfigTemplateParamsWithContext(ctx context.Context) *V2UpdatePoolTemplateConfigTemplateParams {
	var ()
	return &V2UpdatePoolTemplateConfigTemplateParams{

		Context: ctx,
	}
}

// NewV2UpdatePoolTemplateConfigTemplateParamsWithHTTPClient creates a new V2UpdatePoolTemplateConfigTemplateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV2UpdatePoolTemplateConfigTemplateParamsWithHTTPClient(client *http.Client) *V2UpdatePoolTemplateConfigTemplateParams {
	var ()
	return &V2UpdatePoolTemplateConfigTemplateParams{
		HTTPClient: client,
	}
}

/*V2UpdatePoolTemplateConfigTemplateParams contains all the parameters to send to the API endpoint
for the v2 update pool template config template operation typically these are written to a http.Request
*/
type V2UpdatePoolTemplateConfigTemplateParams struct {

	/*Name*/
	Name string
	/*Template*/
	Template string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v2 update pool template config template params
func (o *V2UpdatePoolTemplateConfigTemplateParams) WithTimeout(timeout time.Duration) *V2UpdatePoolTemplateConfigTemplateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v2 update pool template config template params
func (o *V2UpdatePoolTemplateConfigTemplateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v2 update pool template config template params
func (o *V2UpdatePoolTemplateConfigTemplateParams) WithContext(ctx context.Context) *V2UpdatePoolTemplateConfigTemplateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v2 update pool template config template params
func (o *V2UpdatePoolTemplateConfigTemplateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v2 update pool template config template params
func (o *V2UpdatePoolTemplateConfigTemplateParams) WithHTTPClient(client *http.Client) *V2UpdatePoolTemplateConfigTemplateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v2 update pool template config template params
func (o *V2UpdatePoolTemplateConfigTemplateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the v2 update pool template config template params
func (o *V2UpdatePoolTemplateConfigTemplateParams) WithName(name string) *V2UpdatePoolTemplateConfigTemplateParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the v2 update pool template config template params
func (o *V2UpdatePoolTemplateConfigTemplateParams) SetName(name string) {
	o.Name = name
}

// WithTemplate adds the template to the v2 update pool template config template params
func (o *V2UpdatePoolTemplateConfigTemplateParams) WithTemplate(template string) *V2UpdatePoolTemplateConfigTemplateParams {
	o.SetTemplate(template)
	return o
}

// SetTemplate adds the template to the v2 update pool template config template params
func (o *V2UpdatePoolTemplateConfigTemplateParams) SetTemplate(template string) {
	o.Template = template
}

// WriteToRequest writes these params to a swagger request
func (o *V2UpdatePoolTemplateConfigTemplateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.Template); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
