// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/iss-lab/edgelb-config-helper/models"
)

// V2UpdatePoolTemplateConfigTemplateReader is a Reader for the V2UpdatePoolTemplateConfigTemplate structure.
type V2UpdatePoolTemplateConfigTemplateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V2UpdatePoolTemplateConfigTemplateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV2UpdatePoolTemplateConfigTemplateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewV2UpdatePoolTemplateConfigTemplateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewV2UpdatePoolTemplateConfigTemplateOK creates a V2UpdatePoolTemplateConfigTemplateOK with default headers values
func NewV2UpdatePoolTemplateConfigTemplateOK() *V2UpdatePoolTemplateConfigTemplateOK {
	return &V2UpdatePoolTemplateConfigTemplateOK{}
}

/*V2UpdatePoolTemplateConfigTemplateOK handles this case with default header values.

Updated pool configuration template
*/
type V2UpdatePoolTemplateConfigTemplateOK struct {
	Payload string
}

func (o *V2UpdatePoolTemplateConfigTemplateOK) Error() string {
	return fmt.Sprintf("[PUT /v2/pooltemplates/{name}/template][%d] v2UpdatePoolTemplateConfigTemplateOK  %+v", 200, o.Payload)
}

func (o *V2UpdatePoolTemplateConfigTemplateOK) GetPayload() string {
	return o.Payload
}

func (o *V2UpdatePoolTemplateConfigTemplateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2UpdatePoolTemplateConfigTemplateDefault creates a V2UpdatePoolTemplateConfigTemplateDefault with default headers values
func NewV2UpdatePoolTemplateConfigTemplateDefault(code int) *V2UpdatePoolTemplateConfigTemplateDefault {
	return &V2UpdatePoolTemplateConfigTemplateDefault{
		_statusCode: code,
	}
}

/*V2UpdatePoolTemplateConfigTemplateDefault handles this case with default header values.

Unexpected error.
*/
type V2UpdatePoolTemplateConfigTemplateDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the v2 update pool template config template default response
func (o *V2UpdatePoolTemplateConfigTemplateDefault) Code() int {
	return o._statusCode
}

func (o *V2UpdatePoolTemplateConfigTemplateDefault) Error() string {
	return fmt.Sprintf("[PUT /v2/pooltemplates/{name}/template][%d] V2UpdatePoolTemplateConfigTemplate default  %+v", o._statusCode, o.Payload)
}

func (o *V2UpdatePoolTemplateConfigTemplateDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *V2UpdatePoolTemplateConfigTemplateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
