// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// PoolType pool type
//
// swagger:model PoolType
type PoolType string

const (

	// PoolTypeStatic captures enum value "static"
	PoolTypeStatic PoolType = "static"

	// PoolTypeTemplateStatic captures enum value "template-static"
	PoolTypeTemplateStatic PoolType = "template-static"

	// PoolTypeTemplateDynamic captures enum value "template-dynamic"
	PoolTypeTemplateDynamic PoolType = "template-dynamic"
)

// for schema
var poolTypeEnum []interface{}

func init() {
	var res []PoolType
	if err := json.Unmarshal([]byte(`["static","template-static","template-dynamic"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		poolTypeEnum = append(poolTypeEnum, v)
	}
}

func (m PoolType) validatePoolTypeEnum(path, location string, value PoolType) error {
	if err := validate.EnumCase(path, location, value, poolTypeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this pool type
func (m PoolType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validatePoolTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
