// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V2CloudProviderAwsTag A named tag with an associated value.
//
// swagger:model V2CloudProviderAwsTag
type V2CloudProviderAwsTag struct {

	// key
	// Max Length: 127
	// Min Length: 1
	Key string `json:"key,omitempty"`

	// value
	// Max Length: 255
	// Min Length: 1
	Value string `json:"value,omitempty"`
}

// Validate validates this v2 cloud provider aws tag
func (m *V2CloudProviderAwsTag) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V2CloudProviderAwsTag) validateKey(formats strfmt.Registry) error {

	if swag.IsZero(m.Key) { // not required
		return nil
	}

	if err := validate.MinLength("key", "body", string(m.Key), 1); err != nil {
		return err
	}

	if err := validate.MaxLength("key", "body", string(m.Key), 127); err != nil {
		return err
	}

	return nil
}

func (m *V2CloudProviderAwsTag) validateValue(formats strfmt.Registry) error {

	if swag.IsZero(m.Value) { // not required
		return nil
	}

	if err := validate.MinLength("value", "body", string(m.Value), 1); err != nil {
		return err
	}

	if err := validate.MaxLength("value", "body", string(m.Value), 255); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V2CloudProviderAwsTag) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V2CloudProviderAwsTag) UnmarshalBinary(b []byte) error {
	var res V2CloudProviderAwsTag
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
