// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V2CloudProviderAwsElbAz v2 cloud provider aws elb az
//
// swagger:model V2CloudProviderAwsElbAz
type V2CloudProviderAwsElbAz struct {

	// Elastic IP address which the ELB is attached to in a specified availability zone.
	ElasticIP string `json:"elasticIP,omitempty"`

	// The name of the availability zone.
	Name string `json:"name,omitempty"`
}

// Validate validates this v2 cloud provider aws elb az
func (m *V2CloudProviderAwsElbAz) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V2CloudProviderAwsElbAz) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V2CloudProviderAwsElbAz) UnmarshalBinary(b []byte) error {
	var res V2CloudProviderAwsElbAz
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
