// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V2PoolMetadataFrontend v2 pool metadata frontend
//
// swagger:model V2PoolMetadataFrontend
type V2PoolMetadataFrontend struct {

	// Array of public, private IP addresses and port. Each entry in the array reflects the endpoint information of a particular pool instance. For example, if there are three pool instances then there would be three entries in the endpoint array.
	Endpoints []*V2PoolMetadataFrontendEndpoint `json:"endpoints"`

	// Name of the frontend in the edge-lb pool.
	Name string `json:"name,omitempty"`
}

// Validate validates this v2 pool metadata frontend
func (m *V2PoolMetadataFrontend) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEndpoints(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V2PoolMetadataFrontend) validateEndpoints(formats strfmt.Registry) error {

	if swag.IsZero(m.Endpoints) { // not required
		return nil
	}

	for i := 0; i < len(m.Endpoints); i++ {
		if swag.IsZero(m.Endpoints[i]) { // not required
			continue
		}

		if m.Endpoints[i] != nil {
			if err := m.Endpoints[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("endpoints" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *V2PoolMetadataFrontend) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V2PoolMetadataFrontend) UnmarshalBinary(b []byte) error {
	var res V2PoolMetadataFrontend
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
